############# English navigation ##############

############# Oxybulle navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "/a-propos/"
weight = 2

[[main]]
name = "Activités"
url = "/activites/"
weight = 3

[[main]]
name = "Contact"
url = "/contact/"
weight = 5

# footer menu
[[footer]]
name = "À propos"
url = "/a-propos/"
weight = 1

[[footer]]
name = "Nous soutenir"
url = "/nous-soutenir/"
weight = 2

[[footer]]
name = "Mentions légales"
url = "/mentionslegales/"
weight = 3
